INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1234',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1235',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1236',1,2,3,4,5);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1237',3,5,3,2,4);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1238',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1239',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1240',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1241',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1242',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1243',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1244',0,0,0,0,0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1234',7, 4);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1235',3, 2);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1236',10, 4);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1237',5, 1);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1238',12, 4);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1239',8, 4);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1240',10, 3);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1241',1, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1242',4, 2);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1243',2, 2);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1244',2, 2);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1245',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1246',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1247',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1248',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1249',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1250',2, 2);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1251',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1252',2, 1);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1253',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1254',2, 4);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1255',2, 1);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1256',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1257',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1258',2, 2);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1259',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1260',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1261',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1262',2, 2);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1263',2, 4);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1264',2, 4);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1265',2, 2);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1266',2, 0);