INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1234',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1235',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1236',1,2,3,4,5);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1237',3,5,3,2,4);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1238',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1239',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1240',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1241',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1242',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1243',0,0,0,0,0);
INSERT INTO STATISTICUSER (User_ID,Livres,Mobilite,Electronique,Notes,Mobilier) VALUES ('1244',0,0,0,0,0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1234',7, 1);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1235',3, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1236',10, 2);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1238',12, 4);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1239',8, 4);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1240',10, 3);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1241',1, 2);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1242',4, 1);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1243',2, 0);
INSERT INTO STATISTICITEM (Item_ID,nClics_Item, Category) VALUES ('1237',8, 3);
