INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1230','Jean','Dupont','JeanDupont','JeanDupont@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1231','Robert','Du Valet','RobertDuValet','RobertDuValet@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1232','Michelle','Zanardi','MichelleZanardi','MichelleZanardi@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1233','Alexandra','Dujardin','AlexandraDujardin','AlexandraDujardin@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1234','Loan','Herault','LoanHerault','LoanHerault@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1235','Guillaume','Comte','GuillaumeComte','GuillaumeComte@gmail.com',0);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1236','Jonathan','Lo','JonathanLo','JonathanLo@gmail.com',1);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1237','Tommaso','Peletta','Tommy','TommasoPeletta@gmail.com',0);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1238','Adrien','Chabert','chabibi','AdrienChabert@yahoo.fr',10);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1239','Patrick','Sardina','PatrickSardina','PatrickSardina@gmail.com',20);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1240','Pierre','Louis','PierreLouis123','PierreLouis@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1241','Xin Ping','Minh','XinPingMinh','XinPingMinh@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1242','Pedro','Cortez','elTaco78','PedroCortez@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1243','Jeanne','Dapunto','JeanneDapunto','JeanneDapunto@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1244','Christelle','Padore','ChristellePadore','ChristellePadore@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1245','Karen','Smith','KarenSmith','KarenSmith@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1246','Maria','Da Silva','MariaDaSilva','MariaDaSilva@gmail.com',100);
INSERT INTO User (User_ID,Name,Surname,Username,Email,Report) VALUES ('1247','Estelle','Grand-Valet','EstelleGrandValet','EstelleGrandValet@gmail.com',100);
